"""Import all node modules to trigger registration."""

from serenityflow.nodes import (  # noqa: F401
    loaders,
    sampling,
    sampling_custom,
    sampling_lanpaint,
    conditioning,
    latent,
    image_io,
    image_ops,
    post_processing,
    mask,
    lora,
    controlnet,
    video,
    utility,
    model_ops,
    model_specific,
    conditioning_extra,
    controlnet_extra,
    ipadapter,
    audio,
    layer_compositing,
    captioning,
    prompt_utils,
    upscale,
    res4lyf,
    face_workflow,
    video_pipeline,
    propost,
)
