"""LanPaint solver — Langevin dynamics inpainting sampler.

Training-free inpainting that uses Langevin dynamics to iteratively refine
the masked region before each denoise step. Works with any diffusion model
(FLUX, SDXL, SD3, etc.) in both flow-matching and VP/VE formulations.

The key insight:
- Score for unmasked region: score_x = -(x_t - x_0)
- Score for masked region: score_y = -(1+lambda)*(x_t - y) + lambda*(x_t - x_0)
- Lambda controls content alignment strength (4.0-10.0 recommended)

Ported from LanPaint (https://github.com/scraed/LanPaint).
"""
from __future__ import annotations

from functools import partial
from typing import Callable, Optional

import torch

from .earlystop import LanPaintEarlyStopper
from .oscillator import StochasticHarmonicOscillator
from .types import LangevinState


class LanPaintSolver:
    """Langevin dynamics inpainting solver.

    Wraps a model forward function and applies constrained Langevin iterations
    at each denoise step to produce seamless inpainting.

    Args:
        model_fn: callable (x, sigma) -> (x_0, x_0_big) returning denoised
            predictions at two CFG scales.
        n_steps: number of Langevin iterations per denoise step.
        friction: SHO friction parameter (10-20 recommended).
        lambda_strength: content alignment strength (4-10 recommended).
        beta: step size ratio between masked/unmasked regions.
        step_size: Langevin step size (0.1-0.5 recommended).
        is_flux: True for FLUX-type flow models.
        is_flow: True for generic flow-matching models.
        early_stop_threshold: convergence threshold (0 = disabled).
        early_stop_patience: consecutive stable steps before stopping.
    """

    def __init__(
        self,
        model_fn: Callable,
        n_steps: int = 5,
        friction: float = 15.0,
        lambda_strength: float = 7.0,
        beta: float = 1.0,
        step_size: float = 0.3,
        is_flux: bool = False,
        is_flow: bool = False,
        early_stop_threshold: float = 0.0,
        early_stop_patience: int = 1,
    ):
        self.model_fn = model_fn
        self.n_steps = n_steps
        self.friction = friction
        self.chara_lamb = lambda_strength
        self.chara_beta = beta
        self.step_size = step_size
        self.is_flux = is_flux
        self.is_flow = is_flow
        self.early_stop_threshold = early_stop_threshold
        self.early_stop_patience = early_stop_patience
        self._img_dim_size: int = 0

    # -- Dimension helpers ---------------------------------------------------

    def _add_dims(self, array: torch.Tensor) -> torch.Tensor:
        """Broadcast 1D tensor to match image dimensions."""
        idx = (slice(None),) + (None,) * (self._img_dim_size - 1)
        return array[idx]

    def _remove_dims(self, array: torch.Tensor) -> torch.Tensor:
        idx = (slice(None),) + (0,) * (self._img_dim_size - 1)
        return array[idx]

    # -- Sigma helpers -------------------------------------------------------

    def _sigma_x(self, abt: torch.Tensor) -> torch.Tensor:
        return abt**0  # ones

    def _sigma_y(self, abt: torch.Tensor) -> torch.Tensor:
        return self.chara_beta * abt**0

    # -- Core algorithm ------------------------------------------------------

    def __call__(
        self,
        x: torch.Tensor,
        sigma: torch.Tensor,
        latent_image: torch.Tensor,
        noise: torch.Tensor,
        latent_mask: torch.Tensor,
        noise_scaling_fn: Optional[Callable] = None,
        n_steps: Optional[int] = None,
    ) -> torch.Tensor:
        """Run LanPaint for one denoise step.

        Args:
            x: current noisy latent (variance-exploding notation).
            sigma: current noise level.
            latent_image: original clean image in latent space (known region).
            noise: noise tensor for the known region replacement.
            latent_mask: binary mask (1 = known/unmasked, 0 = inpaint region).
                Note: this is INVERTED from the user mask. latent_mask=1 means
                the pixel is KNOWN (will be replaced), latent_mask=0 means
                the pixel is UNKNOWN (will be generated by LanPaint).
            noise_scaling_fn: optional function(sigma, noise, latent_image) -> x_t
                for noise scaling in the known region replacement step.
            n_steps: override number of Langevin iterations.

        Returns:
            Denoised latent with mask compositing applied.
        """
        self._img_dim_size = len(x.shape)
        if n_steps is None:
            n_steps = self.n_steps

        # Ensure noise is non-zero
        if torch.mean(torch.abs(noise)) < 1e-8:
            noise = torch.randn_like(noise)

        # Compute unified time representation
        is_flow = self.is_flux or self.is_flow
        if is_flow:
            flow_t = sigma
            abt = (1 - flow_t)**2 / ((1 - flow_t)**2 + flow_t**2)
            ve_sigma = flow_t / (1 - flow_t)
        else:
            ve_sigma = sigma
            abt = 1 / (1 + ve_sigma**2)
            flow_t = (1 - abt)**0.5 / ((1 - abt)**0.5 + abt**0.5)

        current_times = (ve_sigma, abt, flow_t)

        # Replace step: composite known region into x
        if noise_scaling_fn is not None:
            x_known = noise_scaling_fn(sigma, noise, latent_image)
        else:
            if is_flow:
                s = sigma.reshape([sigma.shape[0]] + [1] * (len(noise.shape) - 1))
                x_known = s * noise + (1.0 - s) * latent_image
            else:
                s = sigma.reshape([sigma.shape[0]] + [1] * (len(noise.shape) - 1))
                x_known = latent_image + noise * s

        x = x * (1 - latent_mask) + x_known * latent_mask

        # Convert to variance-preserving notation for Langevin dynamics
        if is_flow:
            x_t = x * (self._add_dims(abt)**0.5 + (1 - self._add_dims(abt))**0.5)
        else:
            x_t = x / (1 + self._add_dims(ve_sigma)**2)**0.5

        # --- Langevin iterations ---
        stopper = LanPaintEarlyStopper.create(
            latent_mask=latent_mask,
            abt=abt,
            threshold=self.early_stop_threshold,
            patience=self.early_stop_patience,
        )

        args = None
        for i in range(n_steps):
            score_func = partial(
                self._score_model,
                y=latent_image,
                mask=latent_mask,
                abt=self._add_dims(abt),
                sigma=self._add_dims(ve_sigma),
                tflow=self._add_dims(flow_t),
            )

            x_t_before = x_t if stopper is not None else None
            prev_args = args

            x_t, args = self._langevin_dynamics(
                x_t, score_func, latent_mask,
                self.step_size * (1 - abt),
                current_times,
                sigma_x=self._add_dims(self._sigma_x(abt)),
                sigma_y=self._add_dims(self._sigma_y(abt)),
                args=args,
            )

            if stopper is not None and stopper.step(
                x_t_before=x_t_before,
                x_t_after=x_t,
                prev_args=prev_args,
                args=args,
            ):
                break

        # Convert back from variance-preserving
        if is_flow:
            x = x_t / (self._add_dims(abt)**0.5 + (1 - self._add_dims(abt))**0.5)
        else:
            x = x_t * (1 + self._add_dims(ve_sigma)**2)**0.5

        # Final denoise
        out, _ = self.model_fn(x, sigma)
        out = out * (1 - latent_mask) + latent_image * latent_mask

        return out

    def _score_model(
        self,
        x_t: torch.Tensor,
        y: torch.Tensor,
        mask: torch.Tensor,
        abt: torch.Tensor,
        sigma: torch.Tensor,
        tflow: torch.Tensor,
    ) -> torch.Tensor:
        """Compute score function combining model prediction + mask constraint.

        For unmasked region: score_x = -(x_t - x_0)  (standard denoising)
        For masked region: score_y = -(1+lambda)*(x_t - y) + lambda*(x_t - x_0_big)
        """
        lamb = self.chara_lamb
        is_flow = self.is_flux or self.is_flow

        if is_flow:
            x = x_t / (abt**0.5 + (1 - abt)**0.5)
            x_0, x_0_big = self.model_fn(x, self._remove_dims(tflow))
        else:
            x = x_t * (1 + sigma**2)**0.5
            x_0, x_0_big = self.model_fn(x, self._remove_dims(sigma))

        score_x = -(x_t - x_0)
        score_y = -(1 + lamb) * (x_t - y) + lamb * (x_t - x_0_big)
        return score_x * (1 - mask) + score_y * mask

    def _langevin_dynamics(
        self,
        x_t: torch.Tensor,
        score: Callable,
        mask: torch.Tensor,
        step_size: torch.Tensor,
        current_times: tuple,
        sigma_x: torch.Tensor,
        sigma_y: torch.Tensor,
        args: Optional[LangevinState] = None,
    ) -> tuple[torch.Tensor, LangevinState]:
        """One Langevin dynamics update step using SHO."""
        if args is not None and not isinstance(args, LangevinState):
            if isinstance(args, tuple):
                if len(args) == 2:
                    args = LangevinState(args[0], args[1], None)
                elif len(args) >= 3:
                    args = LangevinState(args[0], args[1], args[2])

        step_size = self._add_dims(step_size)

        if x_t.device.type == "cuda":
            with torch.autocast(device_type="cuda", dtype=torch.float32):
                step_sizes = self._prepare_step_size(current_times, step_size, sigma_x, sigma_y)
        else:
            step_sizes = self._prepare_step_size(current_times, step_size, sigma_x, sigma_y)
        sigma_val, abt, dtx, dty, Gamma_x, Gamma_y, A_x, A_y, D_x, D_y = step_sizes

        if torch.mean(dtx) <= 0.0:
            return x_t, args

        # Mix parameters by mask
        A = A_x * (1 - mask) + A_y * mask
        D = D_x * (1 - mask) + D_y * mask
        dt = dtx * (1 - mask) + dty * mask
        Gamma = Gamma_x * (1 - mask) + Gamma_y * mask

        def coef_C(xt):
            x0 = xt + score(xt)
            C = (abt**0.5 * x0 - xt) / (1 - abt) + A * xt
            return C, x0

        def _maybe_autocast(device_type):
            if device_type == "cuda":
                return torch.autocast(device_type="cuda", dtype=torch.float32)
            from contextlib import nullcontext
            return nullcontext()

        def advance_time(xt, v, dt_, Gamma_, A_, C_, D_):
            dtype = xt.dtype
            with _maybe_autocast(xt.device.type):
                osc = StochasticHarmonicOscillator(Gamma_, A_, C_, D_)
                xt, v = osc.dynamics(xt, v, dt_)
            return xt.to(dtype), v.to(dtype)

        def advance_time_overdamped(xt, dt_, A_, C_, D_):
            """Overdamped (Gamma -> inf) limit: dx = -Ax dt + C dt + D dW."""
            dtype = xt.dtype
            with _maybe_autocast(xt.device.type):
                A_dt = A_ * dt_
                exp_neg = torch.exp(-A_dt)
                eps = 1e-8
                abs_A = torch.abs(A_)
                k = torch.where(abs_A < eps, dt_, (-torch.expm1(-A_dt)) / A_)
                k2 = torch.where(abs_A < eps, dt_, (-torch.expm1(-2 * A_dt)) / (2 * A_))
                mean = exp_neg * xt + k * C_
                var = (D_**2) * k2
                noise = torch.randn_like(xt) * torch.sqrt(torch.clamp(var, min=0.0))
                xt = mean + noise
            return xt.to(dtype)

        def run_damped(xt, state):
            if state is None:
                v = None
                C, x0 = coef_C(xt)
                xt, v = advance_time(xt, v, dt, Gamma, A, C, D)
            else:
                v, C = state.v, state.C
                xt, v = advance_time(xt, v, dt / 2, Gamma, A, C, D)
                C_new, x0 = coef_C(xt)
                v = v + Gamma**0.5 * (C_new - C) * dt
                xt, v = advance_time(xt, v, dt / 2, Gamma, A, C, D)
                C = C_new
            return xt, LangevinState(v, C, x0)

        def run_overdamped(xt, state):
            if state is None:
                C, x0 = coef_C(xt)
                xt = advance_time_overdamped(xt, dt, A, C, D)
            else:
                C = state.C
                xt = advance_time_overdamped(xt, dt / 2, A, C, D)
                C_new, x0 = coef_C(xt)
                xt = xt + (C_new - C) * dt
                xt = advance_time_overdamped(xt, dt / 2, A, C, D)
                C = C_new
            return xt, LangevinState(None, C, x0)

        # Try damped first, fall back to overdamped on NaN
        try:
            x_t_next, state = run_damped(x_t, args)
            v_next = state.v
            if torch.isnan(x_t_next).any() or (v_next is not None and torch.isnan(v_next).any()):
                raise ValueError("NaN detected in damped dynamics")
            x_t = x_t_next
            return x_t, state
        except Exception:
            x_t, state = run_overdamped(x_t, args)
            return x_t, state

    def _prepare_step_size(self, current_times, step_size, sigma_x, sigma_y):
        """Compute step sizes and SHO parameters for both branches."""
        sigma_val, abt, flow_t = current_times
        sigma_val = self._add_dims(sigma_val)
        abt = self._add_dims(abt)

        dtx = 2 * step_size * sigma_x
        dty = 2 * step_size * sigma_y

        Gamma_hat_x = self.friction**2 * self.step_size * sigma_x / 0.1 * sigma_val**0
        Gamma_hat_y = self.friction**2 * self.step_size * sigma_y / 0.1 * sigma_val**0
        Gamma_hat_x /= 2.0
        Gamma_hat_y /= 2.0

        A_t_x = 1 / (1 - abt) * dtx / 2
        A_t_y = (1 + self.chara_lamb) / (1 - abt) * dty / 2

        A_x = A_t_x / (dtx / 2)
        A_y = A_t_y / (dty / 2)
        Gamma_x = Gamma_hat_x / (dtx / 2)
        Gamma_y = Gamma_hat_y / (dty / 2)

        D_x = (2 * abt**0)**0.5
        D_y = (2 * abt**0)**0.5

        return sigma_val, abt, dtx / 2, dty / 2, Gamma_x, Gamma_y, A_x, A_y, D_x, D_y


__all__ = ["LanPaintSolver"]
